name: project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add these dependencies for the project
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  icon_broken: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter icons configuration
flutter_icons:
  image_path_android: "assets/images/logo.jpg"
  image_path_ios: "assets/images/logo.jpg"
  android: true
  ios: true

# Flutter package configuration
flutter:
  uses-material-design: true

  # Specify assets
  assets:
    - assets/images/

  # Fonts configuration
  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf